name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
    push:
      paths:
         - p1/**
jobs:
    coverage:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./p1/
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
