name: 'coverage'
on:
  push:
      paths:
         - p1/**
  pull_request:
    branches: [ "main" ]
jobs:
    coverage:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./p1/
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
             with:
              working-directory: ./p1/
              
